appname = oikos_api
httpport = ${OIKOS_API__HTTPPORT}
runmode = ${OIKOS_API__RUNMODE||prod}
autorender = false
copyrequestbody = true
enabledocs = ${OIKOS_API__ENABLEDOCS||true}
parameterStore = ${PARAMETER_STORE}
PGuser = ${OIKOS_API__PGUSER}
PGpass = ${OIKOS_API__PGPASS}
PGhost = ${OIKOS_API__PGURLS}
PGport = ${OIKOS_API__PGPORT||5432}
PGdb   = ${OIKOS_API__PGDB}
PGschema = ${OIKOS_API__PGSCHEMA}
